ROLE_PRESETS = [
    {
        "name": "3O",
        "type": "1night",
        "num_players": 3,
        "roles": ["村人", "占い師", "怪盗", "人狼", "人狼"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 240,
        "vote_time": 90,
        "revote_time": 0,
        "night_time": 60
    },
    {
        "name": "4O",
        "type": "1night",
        "num_players": 4,
        "roles": ["村人", "村人", "占い師", "怪盗", "人狼", "狂人"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 300,
        "vote_time": 90,
        "revote_time": 0,
        "night_time": 60
    },
    {
        "name": "5O",
        "type": "1night",
        "num_players": 5,
        "roles": ["村人", "村人", "村人", "占い師", "怪盗", "人狼", "人狼"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 360,
        "vote_time": 90,
        "revote_time": 0,
        "night_time": 60
    },
    {
        "name": "6O",
        "type": "1night",
        "num_players": 6,
        "roles": ["村人", "村人", "占い師", "占い師", "怪盗", "人狼", "人狼", "狂人"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 420,
        "vote_time": 90,
        "revote_time": 0,
        "night_time": 60
    },
    {
        "name": "7A",
        "type": "normal",
        "num_players": 7,
        "roles": ["村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 240,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "7B",
        "type": "normal",
        "num_players": 7,
        "roles": ["村人", "村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 240,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "7C",
        "type": "normal",
        "num_players": 7,
        "roles": ["村人", "占い師", "霊媒師", "共有者", "共有者", "人狼", "人狼", "狂人"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 240,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "8A",
        "type": "normal",
        "num_players": 8,
        "roles": ["村人", "村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 300,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "8B",
        "type": "normal",
        "num_players": 8,
        "roles": ["村人", "村人", "村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 300,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "8C",
        "type": "normal",
        "num_players": 8,
        "roles": ["村人", "村人", "村人", "占い師", "騎士", "猫又", "人狼", "人狼", "狂人"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 300,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "9A",
        "type": "normal",
        "num_players": 9,
        "roles": ["村人", "村人", "村人", "占い師", "霊媒師", "騎士", "人狼", "人狼", "狂人"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 360,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "9B",
        "type": "normal",
        "num_players": 9,
        "roles": ["村人", "村人", "村人", "村人", "占い師", "霊媒師", "騎士", "人狼", "人狼", "狂人"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 360,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "9C",
        "type": "normal",
        "num_players": 9,
        "roles": ["村人", "村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼", "狐"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": True,
        "day_time": 360,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "10A",
        "type": "normal",
        "num_players": 10,
        "roles": ["村人", "村人", "村人", "村人", "占い師", "霊媒師", "騎士", "人狼", "人狼", "狂人"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": False,
        "day_time": 420,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "10B",
        "type": "normal",
        "num_players": 10,
        "roles": ["村人", "村人", "村人", "村人", "村人", "占い師", "霊媒師", "騎士", "人狼", "人狼", "狂人"],
        "missing_role": True,
        "1st_night_div": True,
        "draw": False,
        "day_time": 420,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    },
    {
        "name": "10C",
        "type": "normal",
        "num_players": 10,
        "roles": ["村人", "村人", "村人", "村人", "村人", "占い師", "騎士", "人狼", "人狼", "狐"],
        "missing_role": False,
        "1st_night_div": False,
        "draw": True,
        "day_time": 420,
        "vote_time": 60,
        "revote_time": 30,
        "night_time": 60
    }
]
